LIST = {
'marccountry': # MARC_COUNTRY_CODE_DICT
{
'aa': 'Asia',
'abc': 'Afghanistan',
'ac': 'Armenia (Republic)',
'aca': 'Azerbaijan',
'ae': 'Bahrain',
'af': 'Bangladesh',
'ag': 'Borneo',
'ai': 'Burma',
'ai': 'Bhutan',
'air': 'Brunei',
'aj': 'Cambodia',
'ajr': 'China',
'aku': 'Anhui Sheng (China)',
'alu': 'Zhejiang Sheng (China)',
'am': 'Chongqing (China)',
'an': 'Fujian Sheng (China)',
'ao': 'Hainan Sheng (China)',
'aq': 'Heilongjiang Sheng (China)',
'aru': 'Hubei Sheng (China)',
'as': 'Hong Kong (China)',
'at': 'Henan Sheng (China)',
'au': 'Hebei Sheng (China)',
'aw': 'Hunan Sheng (China)',
'ay': 'Inner Mongolia (China)',
'azu': 'Gansu Sheng (China)',
'ba': 'Guangxi Zhuangzu Zizhiqu (China)',
'bb': 'Jiangxi Sheng (China)',
'bcc': 'Guangdong Sheng (China)',
'bd': 'Jilin Sheng (China)',
'be': 'Jiangsu Sheng (China)',
'bf': 'Guizhou Sheng (China)',
'bg': 'Liaoning Sheng (China)',
'bh': 'Macau (China : Special Administrative Region)',
'bi': 'Ningxia Huizu Zizhiqu (China)',
'bl': 'Beijing (China)',
'bm': 'Shanxi Sheng (China)',
'bn': 'Shanghai (China)',
'bo': 'Shandong Sheng (China)',
'bp': 'Shaanxi Sheng (China)',
'br': 'Xinjiang Uygur Zizhiqu (China)',
'bs': 'Sichuan Sheng (China)',
'bt': 'Tibet (China)',
'bu': 'Tianjin (China)',
'bv': 'Qinghai Sheng (China)',
'bw': 'Yunnan Sheng (China)',
'bwr': 'Yangtze River (China)',
'bx': 'Kunlun Mountains (China and India)',
'ca': 'Bo Hai (China)',
'cau': 'Xi River (China)',
'cb': 'Yellow River (China)',
'cc': 'Sri Lanka',
'cd': 'Taiwan',
'ce': 'Cyprus',
'cf': 'Timor-Leste',
'cg': 'Georgia (Republic)',
'ch': 'Hong Kong',
'ci': 'India',
'cj': 'Indonesia',
'ck': 'Iraq',
'cl': 'Iran',
'cm': 'Israel',
'cn': 'Japan',
'co': 'Jordan',
'cou': 'Kyrgyzstan',
'cp': 'Korea (North)',
'cq': 'Korea (South)',
'cr': 'Korea',
'cs': 'Kuwait',
'ctu': 'Kazakhstan',
'cu': 'Lebanon',
'cv': 'Laos',
'cw': 'Macao',
'cx': 'Oman',
'cy': 'Mongolia',
'cz': 'Malaysia',
'dcu': 'Nepal',
'deu': 'New Guinea',
'dk': 'Okinawa',
'dm': 'Philippines',
'dq': 'Pakistan',
'dr': 'Papua New Guinea',
'ea': 'Portuguese Timor',
'ec': 'Qatar',
'eg': 'Singapore',
'em': 'Sikkim',
'enk': 'Saudi Arabia',
'er': 'Syria',
'err': 'Tajikistan',
'es': 'Thailand',
'et': 'Turkmenistan',
'fa': 'United Arab Emirates',
'fg': 'Turkey',
'fi': 'Uzbekistan',
'fj': 'Viet Nam, North',
'fk': 'Viet Nam, South',
'flu': 'Vietnam',
'fm': 'Yemen (Republic)',
'fp': 'Yemen (People\'s Democratic Republic)',
'fr': 'Amur River (China and Russia)',
'fs': 'Bengal, Bay of',
'ft': 'Asia, Central',
'gau': 'East Asia',
'gb': 'Thailand, Gulf of',
'gd': 'Mekong River',
'ge': 'Himalaya Mountains',
'gg': 'Indochina',
'gh': 'Caspian Sea',
'gi': 'Malaya',
'gl': 'East China Sea',
'gm': 'South China Sea',
'gn': 'Paracel Islands',
'go': 'Spratly Islands',
'gp': 'Persian Gulf',
'gr': 'Arabian Peninsula',
'gs': 'Southeast Asia',
'gsr': 'Tien Shan',
'gt': 'Arabian Sea',
'gu': 'Middle East',
'gv': 'West Bank',
'gw': 'Gaza Strip',
'gy': 'Israel-Syria Demilitarized Zones',
'gz': 'Israel-Jordan Demilitarized Zones',
'hiu': 'Iraq-Saudi Arabia Neutral Zone',
'hk': 'Yellow Sea',
'hm': 'South Asia',
'ho': 'Commonwealth countries',
'ht': 'Intercontinental areas (Western Hemisphere)',
'hu': 'Caribbean Area; Caribbean Sea',
'iau': 'Latin America',
'ic': 'Middle America',
'idu': 'Circumcaribbean',
'ie': 'Developing countries',
'ii': 'Developed countries',
'ilu': 'Europe',
'im': 'Albania',
'inu': 'Andorra',
'io': 'Austria',
'iq': 'Belgium',
'ir': 'Bosnia and Herzegovina',
'is': 'Bulgaria',
'it': 'Belarus',
'iu': 'Croatia',
'iv': 'Czechoslovakia',
'iw': 'Denmark',
'iy': 'Estonia',
'ja': 'Finland',
'je': 'France',
'ji': 'Germany (East)',
'jm': 'Guernsey',
'jn': 'Gibraltar',
'jo': 'Greece',
'ke': 'Germany (West)',
'kg': 'Germany',
'kgr': 'Hungary',
'kn': 'Iceland',
'ko': 'Ireland',
'ksu': 'Isle of Man',
'ku': 'Italy',
'kv': 'Jersey',
'kyu': 'Kosovo',
'kz': 'Liechtenstein',
'kzr': 'Lithuania',
'lau': 'Luxembourg',
'lb': 'Latvia',
'le': 'Monaco',
'lh': 'Malta',
'li': 'Montenegro',
'lir': 'Moldova',
'ln': 'Netherlands',
'lo': 'Norway',
'ls': 'Poland',
'lu': 'Portugal',
'lv': 'Serbia',
'lvr': 'Romania',
'ly': 'Russia (Federation)',
'mau': 'San Marino',
'mbc': 'Spain',
'mc': 'Sweden',
'mdu': 'Switzerland',
'meu': 'Great Britain',
'mf': 'England',
'mg': 'Northern Ireland',
'mh': 'Scotland',
'miu': 'Great Britain Miscellaneous Island Dependencies',
'mj': 'Wales',
'mk': 'Ukraine',
'ml': 'Russia. Russian Empire. Soviet Union. Former Soviet Republics',
'mm': 'Armenia (Republic)',
'mnu': 'Azerbaijan',
'mo': 'Belarus',
'mou': 'Estonia',
'mp': 'Georgia (Republic)',
'mq': 'Kyrgyzstan',
'mr': 'Kazakhstan',
'msu': 'Lithuania',
'mtu': 'Latvia',
'mu': 'Moldova',
'mv': 'Russia (Federation)',
'mvr': 'Tajikistan',
'mw': 'Turkmenistan',
'mx': 'Ukraine',
'my': 'Uzbekistan',
'mz': 'Central Chernozem Region (Russia)',
'na': 'Siberia, Eastern (Russia)',
'nbu': 'Russian Far East (Russia)',
'ncu': 'Caucasus',
'ndu': 'Central Region, RSFSR',
'ne': 'Soviet Union, Northwestern',
'nfc': 'Soviet Central Asia',
'ng': 'Volga River (Russia)',
'nhu': 'Caucasus, Northern (Russia)',
'nik': 'Siberia (Russia)',
'nju': 'Ural Mountains (Russia)',
'nkc': 'Volgo-Viatskii Region, RSFSR',
'nl': 'Siberia, Western (Russia)',
'nm': 'Vatican City',
'nmu': 'North Macedonia',
'nn': 'Slovakia',
'no': 'Czech Republic',
'np': 'Slovenia',
'nq': 'Serbia and Montenegro; Yugoslavia',
'nr': 'Alps',
'nsc': 'Baltic States',
'ntc': 'Europe, Central',
'nu': 'Balkan Peninsula',
'nuc': 'Europe, Eastern',
'nvu': 'Iberian Peninsula',
'nw': 'Benelux countries',
'nx': 'Europe, Northern',
'nyu': 'Danube River',
'nz': 'Pyrenees',
'ohu': 'Rhine River',
'oku': 'Europe, Southern',
'onc': 'Europe, East Central',
'oru': 'Scandinavia',
'ot': 'Europe, Western',
'pau': 'Africa',
'pc': 'Algeria',
'pe': 'Angola',
'pf': 'Burundi',
'pg': 'Botswana',
'ph': 'Biafra',
'pic': 'Chad',
'pk': 'Congo (Brazzaville)',
'pl': 'Congo (Democratic Republic)',
'pn': 'Cameroon',
'po': 'Central African Republic',
'pp': 'Benin',
'pr': 'Eritrea',
'pt': 'Equatorial Guinea',
'pw': 'Ethiopia',
'py': 'Djibouti',
'qa': 'Ghana',
'qea': 'Gambia',
'quc': 'Gabon',
'rb': 'Guinea',
're': 'Ifni',
'rh': 'Côte d\'Ivoire',
'riu': 'Kenya',
'rm': 'Liberia',
'ru': 'Lesotho',
'rur': 'Libya',
'rw': 'Madagascar',
'ry': 'Mali',
'sa': 'Morocco',
'sb': 'Mauritania',
'sc': 'Malawi',
'scu': 'Mozambique',
'sd': 'Niger',
'sdu': 'Nigeria',
'se': 'Guinea-Bissau',
'sf': 'Zimbabwe',
'sg': 'Rwanda',
'sh': 'South Africa',
'si': 'South Sudan',
'sj': 'Sao Tome and Principe',
'sk': 'Senegal',
'sl': 'Spanish North Africa',
'sm': 'Sudan',
'sn': 'Sierra Leone',
'snc': 'Somalia',
'so': 'Eswatini',
'sp': 'Western Sahara',
'sq': 'Namibia',
'sr': 'Togo',
'ss': 'Tunisia',
'st': 'Tanzania',
'stk': 'Egypt',
'su': 'Uganda',
'sv': 'Burkina Faso',
'sw': 'Zambia',
'sx': 'Atlas Mountains',
'sy': 'Africa, Sub-Saharan',
'sz': 'Africa, Central',
'ta': 'Sahara',
'tar': 'Africa, Eastern',
'tc': 'Africa, North',
'tg': 'Congo River',
'th': 'Africa, Northeast',
'ti': 'Niger River',
'tk': 'Nile River',
'tkr': 'Sudan (Region)',
'tl': 'Africa, French-speaking Equatorial',
'tma': 'Great Rift Valley',
'tnu': 'Africa, Southern',
'to': 'Suez Canal (Egypt)',
'tr': 'Volta River (Ghana)',
'ts': 'Africa, West',
'tt': 'Zambezi River',
'tu': 'French Community',
'tv': 'Indian Ocean',
'txu': 'British Indian Ocean Territory',
'tz': 'Comoros',
'ua': 'Terres australes et antarctiques françaises',
'uc': 'Heard and McDonald Islands',
'ug': 'Mauritius',
'ui': 'Mayotte',
'uik': 'Réunion',
'uk': 'Seychelles',
'un': 'Christmas Island (Indian Ocean)',
'unr': 'Cocos (Keeling) Islands',
'up': 'Maldives',
'ur': 'Socotra Island',
'us': 'Atlantic Ocean',
'utu': 'North Atlantic Ocean',
'uv': 'Azores',
'uy': 'Bermuda Islands',
'uz': 'Canary Islands',
'uzr': 'Cabo Verde',
'vau': 'Faroe Islands',
'vb': 'Jan Mayen Island',
'vc': 'Madeira Islands',
've': 'Svalbard (Norway)',
'vi': 'South Atlantic Ocean',
'vm': 'Ascension Island (Atlantic Ocean)',
'vn': 'Bouvet Island',
'vp': 'Falkland Islands',
'vra': 'Tristan da Cunha',
'vs': 'Saint Helena',
'vtu': 'South Georgia and South Sandwich Islands',
'wau': 'Intercontinental areas (Eastern Hemisphere)',
'wb': 'Arab countries',
'wea': 'Black Sea',
'wf': 'Eurasia',
'wiu': 'Mediterranean Region; Mediterranean Sea',
'wj': 'Red Sea',
'wk': 'North America',
'wlk': 'Canada',
'ws': 'Alberta',
'wvu': 'British Columbia',
'wyu': 'Manitoba',
'xa': 'Newfoundland and Labrador',
'xb': 'New Brunswick',
'xc': 'Nova Scotia',
'xd': 'Northwest Territories',
'xe': 'Nunavut',
'xf': 'Ontario',
'xga': 'Prince Edward Island',
'xh': 'Québec (Province)',
'xi': 'Saskatchewan',
'xj': 'Yukon Territory',
'xk': 'Hudson Bay',
'xl': 'Maritime Provinces',
'xm': 'Prairie Provinces',
'xn': 'Greenland',
'xna': 'Mexico',
'xo': 'United States',
'xoa': 'Alaska',
'xp': 'Alabama',
'xr': 'Arkansas',
'xra': 'Arizona',
'xs': 'California',
'xv': 'Colorado',
'xx': 'Connecticut',
'xxc': 'Washington (D.C.)',
'xxk': 'Delaware',
'xxr': 'Florida',
'xxu': 'Georgia',
'ye': 'Hawaii',
'ykc': 'Iowa',
'ys': 'Idaho',
'yu': 'Illinois',
'za': 'Indiana',
},
'marcgac': # MARC_GEOGRAPHIC_AREAS_CODE_DICT
{
'a': 'Asia',
'a-af': 'Afghanistan',
'a-ai': 'Armenia (Republic)',
'a-aj': 'Azerbaijan',
'a-ba': 'Bahrain',
'a-bg': 'Bangladesh',
'a-bn': 'Borneo',
'a-br': 'Burma',
'a-bt': 'Bhutan',
'a-bx': 'Brunei',
'a-cb': 'Cambodia',
'a-cc': 'China',
'a-cc-an': 'Anhui Sheng (China)',
'a-cc-ch': 'Zhejiang Sheng (China)',
'a-cc-cq': 'Chongqing (China)',
'a-cc-fu': 'Fujian Sheng (China)',
'a-cc-ha': 'Hainan Sheng (China)',
'a-cc-he': 'Heilongjiang Sheng (China)',
'a-cc-hh': 'Hubei Sheng (China)',
'a-cc-hk': 'Hong Kong (China)',
'a-cc-ho': 'Henan Sheng (China)',
'a-cc-hp': 'Hebei Sheng (China)',
'a-cc-hu': 'Hunan Sheng (China)',
'a-cc-im': 'Inner Mongolia (China)',
'a-cc-ka': 'Gansu Sheng (China)',
'a-cc-kc': 'Guangxi Zhuangzu Zizhiqu (China)',
'a-cc-ki': 'Jiangxi Sheng (China)',
'a-cc-kn': 'Guangdong Sheng (China)',
'a-cc-kr': 'Jilin Sheng (China)',
'a-cc-ku': 'Jiangsu Sheng (China)',
'a-cc-kw': 'Guizhou Sheng (China)',
'a-cc-lp': 'Liaoning Sheng (China)',
'a-cc-mh': 'Macau (China : Special Administrative Region)',
'a-cc-nn': 'Ningxia Huizu Zizhiqu (China)',
'a-cc-pe': 'Beijing (China)',
'a-cc-sh': 'Shanxi Sheng (China)',
'a-cc-sm': 'Shanghai (China)',
'a-cc-sp': 'Shandong Sheng (China)',
'a-cc-ss': 'Shaanxi Sheng (China)',
'a-cc-su': 'Xinjiang Uygur Zizhiqu (China)',
'a-cc-sz': 'Sichuan Sheng (China)',
'a-cc-ti': 'Tibet (China)',
'a-cc-tn': 'Tianjin (China)',
'a-cc-ts': 'Qinghai Sheng (China)',
'a-cc-yu': 'Yunnan Sheng (China)',
'a-ccg': 'Yangtze River (China)',
'a-cck': 'Kunlun Mountains (China and India)',
'a-ccp': 'Bo Hai (China)',
'a-ccs': 'Xi River (China)',
'a-ccy': 'Yellow River (China)',
'a-ce': 'Sri Lanka',
'a-ch': 'Taiwan',
'a-cy': 'Cyprus',
'a-em': 'Timor-Leste',
'a-gs': 'Georgia (Republic)',
'a-hk': 'Hong Kong',
'a-ii': 'India',
'a-io': 'Indonesia',
'a-iq': 'Iraq',
'a-ir': 'Iran',
'a-is': 'Israel',
'a-ja': 'Japan',
'a-jo': 'Jordan',
'a-kg': 'Kyrgyzstan',
'a-kn': 'Korea (North)',
'a-ko': 'Korea (South)',
'a-kr': 'Korea',
'a-ku': 'Kuwait',
'a-kz': 'Kazakhstan',
'a-le': 'Lebanon',
'a-ls': 'Laos',
'a-mh': 'Macao',
'a-mk': 'Oman',
'a-mp': 'Mongolia',
'a-my': 'Malaysia',
'a-np': 'Nepal',
'a-nw': 'New Guinea',
'a-ok': 'Okinawa',
'a-ph': 'Philippines',
'a-pk': 'Pakistan',
'a-pp': 'Papua New Guinea',
'a-pt': 'Portuguese Timor',
'a-qa': 'Qatar',
'a-si': 'Singapore',
'a-sk': 'Sikkim',
'a-su': 'Saudi Arabia',
'a-sy': 'Syria',
'a-ta': 'Tajikistan',
'a-th': 'Thailand',
'a-tk': 'Turkmenistan',
'a-ts': 'United Arab Emirates',
'a-tu': 'Turkey',
'a-uz': 'Uzbekistan',
'a-vn': 'Viet Nam, North',
'a-vs': 'Viet Nam, South',
'a-vt': 'Vietnam',
'a-ye': 'Yemen (Republic)',
'a-ys': 'Yemen (People\'s Democratic Republic)',
'aa': 'Amur River (China and Russia)',
'ab': 'Bengal, Bay of',
'ac': 'Asia, Central',
'ae': 'East Asia',
'af': 'Thailand, Gulf of',
'ag': 'Mekong River',
'ah': 'Himalaya Mountains',
'ai': 'Indochina',
'ak': 'Caspian Sea',
'am': 'Malaya',
'an': 'East China Sea',
'ao': 'South China Sea',
'aopf': 'Paracel Islands',
'aoxp': 'Spratly Islands',
'ap': 'Persian Gulf',
'ar': 'Arabian Peninsula',
'as': 'Southeast Asia',
'at': 'Tien Shan',
'au': 'Arabian Sea',
'aw': 'Middle East',
'awba': 'West Bank',
'awgz': 'Gaza Strip',
'awiu': 'Israel-Syria Demilitarized Zones',
'awiw': 'Israel-Jordan Demilitarized Zones',
'awiy': 'Iraq-Saudi Arabia Neutral Zone',
'ay': 'Yellow Sea',
'az': 'South Asia',
'b': 'Commonwealth countries',
'c': 'Intercontinental areas (Western Hemisphere)',
'cc': 'Caribbean Area; Caribbean Sea',
'cl': 'Latin America',
'cm': 'Middle America',
'cr': 'Circumcaribbean',
'd': 'Developing countries',
'dd': 'Developed countries',
'e': 'Europe',
'e-aa': 'Albania',
'e-an': 'Andorra',
'e-au': 'Austria',
'e-be': 'Belgium',
'e-bn': 'Bosnia and Herzegovina',
'e-bu': 'Bulgaria',
'e-bw': 'Belarus',
'e-ci': 'Croatia',
'e-cs': 'Czechoslovakia',
'e-dk': 'Denmark',
'e-er': 'Estonia',
'e-fi': 'Finland',
'e-fr': 'France',
'e-ge': 'Germany (East)',
'e-gg': 'Guernsey',
'e-gi': 'Gibraltar',
'e-gr': 'Greece',
'e-gw': 'Germany (West)',
'e-gx': 'Germany',
'e-hu': 'Hungary',
'e-ic': 'Iceland',
'e-ie': 'Ireland',
'e-im': 'Isle of Man',
'e-it': 'Italy',
'e-je': 'Jersey',
'e-kv': 'Kosovo',
'e-lh': 'Liechtenstein',
'e-li': 'Lithuania',
'e-lu': 'Luxembourg',
'e-lv': 'Latvia',
'e-mc': 'Monaco',
'e-mm': 'Malta',
'e-mo': 'Montenegro',
'e-mv': 'Moldova',
'e-ne': 'Netherlands',
'e-no': 'Norway',
'e-pl': 'Poland',
'e-po': 'Portugal',
'e-rb': 'Serbia',
'e-rm': 'Romania',
'e-ru': 'Russia (Federation)',
'e-sm': 'San Marino',
'e-sp': 'Spain',
'e-sw': 'Sweden',
'e-sz': 'Switzerland',
'e-uk': 'Great Britain',
'e-uk-en': 'England',
'e-uk-ni': 'Northern Ireland',
'e-uk-st': 'Scotland',
'e-uk-ui': 'Great Britain Miscellaneous Island Dependencies',
'e-uk-wl': 'Wales',
'e-un': 'Ukraine',
'e-ur': 'Russia. Russian Empire. Soviet Union. Former Soviet Republics',
'e-ur-ai': 'Armenia (Republic)',
'e-ur-aj': 'Azerbaijan',
'e-ur-bw': 'Belarus',
'e-ur-er': 'Estonia',
'e-ur-gs': 'Georgia (Republic)',
'e-ur-kg': 'Kyrgyzstan',
'e-ur-kz': 'Kazakhstan',
'e-ur-li': 'Lithuania',
'e-ur-lv': 'Latvia',
'e-ur-mv': 'Moldova',
'e-ur-ru': 'Russia (Federation)',
'e-ur-ta': 'Tajikistan',
'e-ur-tk': 'Turkmenistan',
'e-ur-un': 'Ukraine',
'e-ur-uz': 'Uzbekistan',
'e-urc': 'Central Chernozem Region (Russia)',
'e-ure': 'Siberia, Eastern (Russia)',
'e-urf': 'Russian Far East (Russia)',
'e-urk': 'Caucasus',
'e-url': 'Central Region, RSFSR',
'e-urn': 'Soviet Union, Northwestern',
'e-uro': 'Soviet Central Asia',
'e-urp': 'Volga River (Russia)',
'e-urr': 'Caucasus, Northern (Russia)',
'e-urs': 'Siberia (Russia)',
'e-uru': 'Ural Mountains (Russia)',
'e-urv': 'Volgo-Viatskii Region, RSFSR',
'e-urw': 'Siberia, Western (Russia)',
'e-vc': 'Vatican City',
'e-xn': 'North Macedonia',
'e-xo': 'Slovakia',
'e-xr': 'Czech Republic',
'e-xv': 'Slovenia',
'e-yu': 'Serbia and Montenegro; Yugoslavia',
'ea': 'Alps',
'eb': 'Baltic States',
'ec': 'Europe, Central',
'ed': 'Balkan Peninsula',
'ee': 'Europe, Eastern',
'ei': 'Iberian Peninsula',
'el': 'Benelux countries',
'en': 'Europe, Northern',
'eo': 'Danube River',
'ep': 'Pyrenees',
'er': 'Rhine River',
'es': 'Europe, Southern',
'et': 'Europe, East Central',
'ev': 'Scandinavia',
'ew': 'Europe, Western',
'f': 'Africa',
'f-ae': 'Algeria',
'f-ao': 'Angola',
'f-bd': 'Burundi',
'f-bs': 'Botswana',
'f-by': 'Biafra',
'f-cd': 'Chad',
'f-cf': 'Congo (Brazzaville)',
'f-cg': 'Congo (Democratic Republic)',
'f-cm': 'Cameroon',
'f-cx': 'Central African Republic',
'f-dm': 'Benin',
'f-ea': 'Eritrea',
'f-eg': 'Equatorial Guinea',
'f-et': 'Ethiopia',
'f-ft': 'Djibouti',
'f-gh': 'Ghana',
'f-gm': 'Gambia',
'f-go': 'Gabon',
'f-gv': 'Guinea',
'f-if': 'Ifni',
'f-iv': 'Côte d\'Ivoire',
'f-ke': 'Kenya',
'f-lb': 'Liberia',
'f-lo': 'Lesotho',
'f-ly': 'Libya',
'f-mg': 'Madagascar',
'f-ml': 'Mali',
'f-mr': 'Morocco',
'f-mu': 'Mauritania',
'f-mw': 'Malawi',
'f-mz': 'Mozambique',
'f-ng': 'Niger',
'f-nr': 'Nigeria',
'f-pg': 'Guinea-Bissau',
'f-rh': 'Zimbabwe',
'f-rw': 'Rwanda',
'f-sa': 'South Africa',
'f-sd': 'South Sudan',
'f-sf': 'Sao Tome and Principe',
'f-sg': 'Senegal',
'f-sh': 'Spanish North Africa',
'f-sj': 'Sudan',
'f-sl': 'Sierra Leone',
'f-so': 'Somalia',
'f-sq': 'Eswatini',
'f-ss': 'Western Sahara',
'f-sx': 'Namibia',
'f-tg': 'Togo',
'f-ti': 'Tunisia',
'f-tz': 'Tanzania',
'f-ua': 'Egypt',
'f-ug': 'Uganda',
'f-uv': 'Burkina Faso',
'f-za': 'Zambia',
'fa': 'Atlas Mountains',
'fb': 'Africa, Sub-Saharan',
'fc': 'Africa, Central',
'fd': 'Sahara',
'fe': 'Africa, Eastern',
'ff': 'Africa, North',
'fg': 'Congo River',
'fh': 'Africa, Northeast',
'fi': 'Niger River',
'fl': 'Nile River',
'fn': 'Sudan (Region)',
'fq': 'Africa, French-speaking Equatorial',
'fr': 'Great Rift Valley',
'fs': 'Africa, Southern',
'fu': 'Suez Canal (Egypt)',
'fv': 'Volta River (Ghana)',
'fw': 'Africa, West',
'fz': 'Zambezi River',
'h': 'French Community',
'i': 'Indian Ocean',
'i-bi': 'British Indian Ocean Territory',
'i-cq': 'Comoros',
'i-fs': 'Terres australes et antarctiques françaises',
'i-hm': 'Heard and McDonald Islands',
'i-mf': 'Mauritius',
'i-my': 'Mayotte',
'i-re': 'Réunion',
'i-se': 'Seychelles',
'i-xa': 'Christmas Island (Indian Ocean)',
'i-xb': 'Cocos (Keeling) Islands',
'i-xc': 'Maldives',
'i-xo': 'Socotra Island',
'l': 'Atlantic Ocean',
'ln': 'North Atlantic Ocean',
'lnaz': 'Azores',
'lnbm': 'Bermuda Islands',
'lnca': 'Canary Islands',
'lncv': 'Cabo Verde',
'lnfa': 'Faroe Islands',
'lnjn': 'Jan Mayen Island',
'lnma': 'Madeira Islands',
'lnsb': 'Svalbard (Norway)',
'ls': 'South Atlantic Ocean',
'lsai': 'Ascension Island (Atlantic Ocean)',
'lsbv': 'Bouvet Island',
'lsfk': 'Falkland Islands',
'lstd': 'Tristan da Cunha',
'lsxj': 'Saint Helena',
'lsxs': 'South Georgia and South Sandwich Islands',
'm': 'Intercontinental areas (Eastern Hemisphere)',
'ma': 'Arab countries',
'mb': 'Black Sea',
'me': 'Eurasia',
'mm': 'Mediterranean Region; Mediterranean Sea',
'mr': 'Red Sea',
'n': 'North America',
'n-cn': 'Canada',
'n-cn-ab': 'Alberta',
'n-cn-bc': 'British Columbia',
'n-cn-mb': 'Manitoba',
'n-cn-nf': 'Newfoundland and Labrador',
'n-cn-nk': 'New Brunswick',
'n-cn-ns': 'Nova Scotia',
'n-cn-nt': 'Northwest Territories',
'n-cn-nu': 'Nunavut',
'n-cn-on': 'Ontario',
'n-cn-pi': 'Prince Edward Island',
'n-cn-qu': 'Québec (Province)',
'n-cn-sn': 'Saskatchewan',
'n-cn-yk': 'Yukon Territory',
'n-cnh': 'Hudson Bay',
'n-cnm': 'Maritime Provinces',
'n-cnp': 'Prairie Provinces',
'n-gl': 'Greenland',
'n-mx': 'Mexico',
'n-us': 'United States',
'n-us-ak': 'Alaska',
'n-us-al': 'Alabama',
'n-us-ar': 'Arkansas',
'n-us-az': 'Arizona',
'n-us-ca': 'California',
'n-us-co': 'Colorado',
'n-us-ct': 'Connecticut',
'n-us-dc': 'Washington (D.C.)',
'n-us-de': 'Delaware',
'n-us-fl': 'Florida',
'n-us-ga': 'Georgia',
'n-us-hi': 'Hawaii',
'n-us-ia': 'Iowa',
'n-us-id': 'Idaho',
'n-us-il': 'Illinois',
'n-us-in': 'Indiana',
'n-us-ks': 'Kansas',
'n-us-ky': 'Kentucky',
'n-us-la': 'Louisiana',
'n-us-ma': 'Massachusetts',
'n-us-md': 'Maryland',
'n-us-me': 'Maine',
'n-us-mi': 'Michigan',
'n-us-mn': 'Minnesota',
'n-us-mo': 'Missouri',
'n-us-ms': 'Mississippi',
'n-us-mt': 'Montana',
'n-us-nb': 'Nebraska',
'n-us-nc': 'North Carolina',
'n-us-nd': 'North Dakota',
'n-us-nh': 'New Hampshire',
'n-us-nj': 'New Jersey',
'n-us-nm': 'New Mexico',
'n-us-nv': 'Nevada',
'n-us-ny': 'New York',
'n-us-oh': 'Ohio',
'n-us-ok': 'Oklahoma',
'n-us-or': 'Oregon',
'n-us-pa': 'Pennsylvania',
'n-us-ri': 'Rhode Island',
'n-us-sc': 'South Carolina',
'n-us-sd': 'South Dakota',
'n-us-tn': 'Tennessee',
'n-us-tx': 'Texas',
'n-us-ut': 'Utah',
'n-us-va': 'Virginia',
'n-us-vt': 'Vermont',
'n-us-wa': 'Washington (State)',
'n-us-wi': 'Wisconsin',
'n-us-wv': 'West Virginia',
'n-us-wy': 'Wyoming',
'n-usa': 'Appalachian Mountains',
'n-usc': 'Middle West',
'n-use': 'Northeastern States',
'n-usl': 'Middle Atlantic States',
'n-usm': 'Mississippi River',
'n-usn': 'New England',
'n-uso': 'Ohio River',
'n-usp': 'West (U.S.)',
'n-usr': 'East (U.S.)',
'n-uss': 'Missouri River',
'n-ust': 'Southwest, New',
'n-usu': 'Southern States',
'n-usw': 'Northwest (U.S.)',
'n-xl': 'Saint Pierre and Miquelon',
'nc': 'Central America',
'ncbh': 'Belize',
'nccr': 'Costa Rica',
'nccz': 'Canal Zone',
'nces': 'El Salvador',
'ncgt': 'Guatemala',
'ncho': 'Honduras',
'ncnq': 'Nicaragua',
'ncpn': 'Panama',
'nl': 'Great Lakes (North America); Lake States',
'nm': 'Mexico, Gulf of',
'np': 'Great Plains',
'nr': 'Rocky Mountains',
'nw': 'West Indies',
'nwaq': 'Antigua and Barbuda',
'nwaw': 'Aruba',
'nwbb': 'Barbados',
'nwbc': 'Barbuda',
'nwbf': 'Bahamas',
'nwbn': 'Bonaire',
'nwcj': 'Cayman Islands',
'nwco': 'Curaçao',
'nwcu': 'Cuba',
'nwdq': 'Dominica',
'nwdr': 'Dominican Republic',
'nweu': 'Sint Eustatius',
'nwga': 'Greater Antilles',
'nwgd': 'Grenada',
'nwgp': 'Guadeloupe',
'nwgs': 'Grenadines',
'nwhi': 'Hispaniola',
'nwht': 'Haiti',
'nwjm': 'Jamaica',
'nwla': 'Antilles, Lesser',
'nwli': 'Leeward Islands (West Indies)',
'nwmj': 'Montserrat',
'nwmq': 'Martinique',
'nwna': 'Netherlands Antilles',
'nwpr': 'Puerto Rico',
'nwsb': 'Saint-Barthélemy',
'nwsc': 'Saint-Barthélemy',
'nwsd': 'Saba',
'nwsn': 'Sint Maarten',
'nwst': 'Saint-Martin',
'nwsv': 'Swan Islands (Honduras)',
'nwtc': 'Turks and Caicos Islands',
'nwtr': 'Trinidad and Tobago',
'nwuc': 'United States Miscellaneous Caribbean Islands',
'nwvb': 'British Virgin Islands',
'nwvi': 'Virgin Islands of the United States',
'nwvr': 'Virgin Islands',
'nwwi': 'Windward Islands (West Indies)',
'nwxa': 'Anguilla',
'nwxi': 'Saint Kitts and Nevis',
'nwxk': 'Saint Lucia',
'nwxm': 'Saint Vincent and the Grenadines',
'p': 'Pacific Ocean',
'pn': 'North Pacific Ocean',
'po': 'Oceania',
'poas': 'American Samoa',
'pobp': 'Solomon Islands',
'poci': 'Caroline Islands',
'pocp': 'Canton and Enderbury Islands',
'pocw': 'Cook Islands',
'poea': 'Easter Island',
'pofj': 'Fiji',
'pofp': 'French Polynesia',
'pogg': 'Galapagos Islands',
'pogn': 'Gilbert and Ellice Islands',
'pogu': 'Guam',
'poji': 'Johnston Island',
'pokb': 'Kiribati',
'poki': 'Kermadec Islands',
'poln': 'Line Islands',
'pome': 'Melanesia',
'pomi': 'Micronesia (Federated States)',
'ponl': 'New Caledonia',
'ponn': 'Vanuatu',
'ponu': 'Nauru',
'popc': 'Pitcairn Island',
'popl': 'Palau',
'pops': 'Polynesia',
'pory': 'Ryukyu Islands, Southern',
'posc': 'Santa Cruz Islands',
'posh': 'Samoan Islands',
'posn': 'Solomon Islands',
'potl': 'Tokelau',
'poto': 'Tonga',
'pott': 'Micronesia',
'potv': 'Tuvalu',
'poup': 'United States Miscellaneous Pacific Islands',
'powf': 'Wallis and Futuna Islands',
'powk': 'Wake Island',
'pows': 'Samoa',
'poxd': 'Mariana Islands',
'poxe': 'Marshall Islands',
'poxf': 'Midway Islands',
'poxh': 'Niue',
'ps': 'South Pacific Ocean',
'q': 'Cold regions',
'r': 'Arctic Ocean; Arctic regions',
's': 'South America',
's-ag': 'Argentina',
's-bl': 'Brazil',
's-bo': 'Bolivia',
's-ck': 'Colombia',
's-cl': 'Chile',
's-ec': 'Ecuador',
's-fg': 'French Guiana',
's-gy': 'Guyana',
's-pe': 'Peru',
's-py': 'Paraguay',
's-sr': 'Suriname',
's-uy': 'Uruguay',
's-ve': 'Venezuela',
'sa': 'Amazon River',
'sn': 'Andes',
'sp': 'Rio de la Plata (Argentina and Uruguay)',
't': 'Antarctic Ocean; Antarctica',
't-ay': 'Antarctica',
'u': 'Australasia',
'u-ac': 'Ashmore and Cartier Islands',
'u-at': 'Australia',
'u-at-ac': 'Australian Capital Territory',
'u-atc': 'Central Australia',
'u-ate': 'Eastern Australia',
'u-atn': 'Northern Australia',
'u-at-ne': 'New South Wales',
'u-at-no': 'Northern Territory',
'u-at-qn': 'Queensland',
'u-at-sa': 'South Australia',
'u-at-tm': 'Tasmania',
'u-at-vi': 'Victoria',
'u-at-we': 'Western Australia',
'u-cs': 'Coral Sea Islands',
'u-nz': 'New Zealand',
'v': 'Communist countries',
'w': 'Tropics',
'x': 'Earth',
'xa': 'Eastern Hemisphere',
'xb': 'Northern Hemisphere',
'xc': 'Southern Hemisphere',
'xd': 'Western Hemisphere',
'zd': 'Deep space',
'zju': 'Jupiter',
'zma': 'Mars',
'zme': 'Mercury',
'zmo': 'Moon',
'zne': 'Neptune',
'zo': 'Outer space',
'zpl': 'Pluto',
'zs': 'Solar system',
'zsa': 'Saturn',
'zsu': 'Sun',
'zur': 'Uranus',
'zve': 'Venus',
},
'iso639-2b': # MARC_LANGUAGE_CODE_DICT
{
'aar': 'Afar',
'abk': 'Abkhaz',
'ace': 'Achinese',
'ach': 'Acoli',
'ada': 'Adangme',
'ady': 'Adygei',
'afa': 'Afroasiatic (Other)',
'afh': 'Afrihili (Artificial language)',
'afr': 'Afrikaans',
'ain': 'Ainu',
'ajm': 'Aljamía',
'aka': 'Akan',
'akk': 'Akkadian',
'alb': 'Albanian',
'ale': 'Aleut',
'alg': 'Algonquian (Other)',
'alt': 'Altai',
'amh': 'Amharic',
'ang': 'English, Old (ca. 450-1100)',
'anp': 'Angika',
'apa': 'Apache languages',
'ara': 'Arabic',
'arc': 'Aramaic',
'arg': 'Aragonese',
'arm': 'Armenian',
'arn': 'Mapuche',
'arp': 'Arapaho',
'art': 'Artificial (Other)',
'arw': 'Arawak',
'asm': 'Assamese',
'ast': 'Bable',
'ath': 'Athapascan (Other)',
'aus': 'Australian languages',
'ava': 'Avaric',
'ave': 'Avestan',
'awa': 'Awadhi',
'aym': 'Aymara',
'aze': 'Azerbaijani',
'bad': 'Banda languages',
'bai': 'Bamileke languages',
'bak': 'Bashkir',
'bal': 'Baluchi',
'bam': 'Bambara',
'ban': 'Balinese',
'baq': 'Basque',
'bas': 'Basa',
'bat': 'Baltic (Other)',
'bej': 'Beja',
'bel': 'Belarusian',
'bem': 'Bemba',
'ben': 'Bengali',
'ber': 'Berber (Other)',
'bho': 'Bhojpuri',
'bih': 'Bihari (Other)',
'bik': 'Bikol',
'bin': 'Edo',
'bis': 'Bislama',
'bla': 'Siksika',
'bnt': 'Bantu (Other)',
'bos': 'Bosnian',
'bra': 'Braj',
'bre': 'Breton',
'btk': 'Batak',
'bua': 'Buriat',
'bug': 'Bugis',
'bul': 'Bulgarian',
'bur': 'Burmese',
'byn': 'Bilin',
'cad': 'Caddo',
'cai': 'Central American Indian (Other)',
'cam': 'Khmer',
'car': 'Carib',
'cat': 'Catalan',
'cau': 'Caucasian (Other)',
'ceb': 'Cebuano',
'cel': 'Celtic (Other)',
'cha': 'Chamorro',
'chb': 'Chibcha',
'che': 'Chechen',
'chg': 'Chagatai',
'chi': 'Chinese',
'chk': 'Chuukese',
'chm': 'Mari',
'chn': 'Chinook jargon',
'cho': 'Choctaw',
'chp': 'Chipewyan',
'chr': 'Cherokee',
'chu': 'Church Slavic',
'chv': 'Chuvash',
'chy': 'Cheyenne',
'cmc': 'Chamic languages',
'cnr': 'Montenegrin',
'cop': 'Coptic',
'cor': 'Cornish',
'cos': 'Corsican',
'cpe': 'Creoles and Pidgins, English-based (Other)',
'cpf': 'Creoles and Pidgins, French-based (Other)',
'cpp': 'Creoles and Pidgins, Portuguese-based (Other)',
'cre': 'Cree',
'crh': 'Crimean Tatar',
'crp': 'Creoles and Pidgins (Other)',
'csb': 'Kashubian',
'cus': 'Cushitic (Other)',
'cze': 'Czech',
'dak': 'Dakota',
'dan': 'Danish',
'dar': 'Dargwa',
'day': 'Dayak',
'del': 'Delaware',
'den': 'Slavey',
'dgr': 'Dogrib',
'din': 'Dinka',
'div': 'Divehi',
'doi': 'Dogri',
'dra': 'Dravidian (Other)',
'dsb': 'Lower Sorbian',
'dua': 'Duala',
'dum': 'Dutch, Middle (ca. 1050-1350)',
'dut': 'Dutch',
'dyu': 'Dyula',
'dzo': 'Dzongkha',
'efi': 'Efik',
'egy': 'Egyptian',
'eka': 'Ekajuk',
'elx': 'Elamite',
'eng': 'English',
'enm': 'English, Middle (1100-1500)',
'epo': 'Esperanto',
'esk': 'Eskimo languages',
'esp': 'Esperanto',
'est': 'Estonian',
'eth': 'Ethiopic',
'ewe': 'Ewe',
'ewo': 'Ewondo',
'fan': 'Fang',
'fao': 'Faroese',
'far': 'Faroese',
'fat': 'Fanti',
'fij': 'Fijian',
'fil': 'Filipino',
'fin': 'Finnish',
'fiu': 'Finno-Ugrian (Other)',
'fon': 'Fon',
'fre': 'French',
'fri': 'Frisian',
'frm': 'French, Middle (ca. 1300-1600)',
'fro': 'French, Old (ca. 842-1300)',
'frr': 'North Frisian',
'frs': 'East Frisian',
'fry': 'Frisian',
'ful': 'Fula',
'fur': 'Friulian',
'gaa': 'Gã',
'gae': 'Scottish Gaelix',
'gag': 'Galician',
'gal': 'Oromo',
'gay': 'Gayo',
'gba': 'Gbaya',
'gem': 'Germanic (Other)',
'geo': 'Georgian',
'ger': 'German',
'gez': 'Ethiopic',
'gil': 'Gilbertese',
'gla': 'Scottish Gaelic',
'gle': 'Irish',
'glg': 'Galician',
'glv': 'Manx',
'gmh': 'German, Middle High (ca. 1050-1500)',
'goh': 'German, Old High (ca. 750-1050)',
'gon': 'Gondi',
'gor': 'Gorontalo',
'got': 'Gothic',
'grb': 'Grebo',
'grc': 'Greek, Ancient (to 1453)',
'gre': 'Greek, Modern (1453-)',
'grn': 'Guarani',
'gsw': 'Swiss German',
'gua': 'Guarani',
'guj': 'Gujarati',
'gwi': 'Gwich\'in',
'hai': 'Haida',
'hat': 'Haitian French Creole',
'hau': 'Hausa',
'haw': 'Hawaiian',
'heb': 'Hebrew',
'her': 'Herero',
'hil': 'Hiligaynon',
'him': 'Western Pahari languages',
'hin': 'Hindi',
'hit': 'Hittite',
'hmn': 'Hmong',
'hmo': 'Hiri Motu',
'hrv': 'Croatian',
'hsb': 'Upper Sorbian',
'hun': 'Hungarian',
'hup': 'Hupa',
'iba': 'Iban',
'ibo': 'Igbo',
'ice': 'Icelandic',
'ido': 'Ido',
'iii': 'Sichuan Yi',
'ijo': 'Ijo',
'iku': 'Inuktitut',
'ile': 'Interlingue',
'ilo': 'Iloko',
'ina': 'Interlingua (International Auxiliary Language Association)',
'inc': 'Indic (Other)',
'ind': 'Indonesian',
'ine': 'Indo-European (Other)',
'inh': 'Ingush',
'int': 'Interlingua (International Auxiliary Language Association)',
'ipk': 'Inupiaq',
'ira': 'Iranian (Other)',
'iri': 'Irish',
'iro': 'Iroquoian (Other)',
'ita': 'Italian',
'jav': 'Javanese',
'jbo': 'Lojban (Artificial language)',
'jpn': 'Japanese',
'jpr': 'Judeo-Persian',
'jrb': 'Judeo-Arabic',
'kaa': 'Kara-Kalpak',
'kab': 'Kabyle',
'kac': 'Kachin',
'kal': 'Kalâtdlisut',
'kam': 'Kamba',
'kan': 'Kannada',
'kar': 'Karen languages',
'kas': 'Kashmiri',
'kau': 'Kanuri',
'kaw': 'Kawi',
'kaz': 'Kazakh',
'kbd': 'Kabardian',
'kha': 'Khasi',
'khi': 'Khoisan (Other)',
'khm': 'Khmer',
'kho': 'Khotanese',
'kik': 'Kikuyu',
'kin': 'Kinyarwanda',
'kir': 'Kyrgyz',
'kmb': 'Kimbundu',
'kok': 'Konkani',
'kom': 'Komi',
'kon': 'Kongo',
'kor': 'Korean',
'kos': 'Kosraean',
'kpe': 'Kpelle',
'krc': 'Karachay-Balkar',
'krl': 'Karelian',
'kro': 'Kru (Other)',
'kru': 'Kurukh',
'kua': 'Kuanyama',
'kum': 'Kumyk',
'kur': 'Kurdish',
'kus': 'Kusaie',
'kut': 'Kootenai',
'lad': 'Ladino',
'lah': 'Lahndā',
'lam': 'Lamba (Zambia and Congo)',
'lan': 'Occitan (post 1500)',
'lao': 'Lao',
'lap': 'Sami',
'lat': 'Latin',
'lav': 'Latvian',
'lez': 'Lezgian',
'lim': 'Limburgish',
'lin': 'Lingala',
'lit': 'Lithuanian',
'lol': 'Mongo-Nkundu',
'loz': 'Lozi',
'ltz': 'Luxembourgish',
'lua': 'Luba-Lulua',
'lub': 'Luba-Katanga',
'lug': 'Ganda',
'lui': 'Luiseño',
'lun': 'Lunda',
'luo': 'Luo (Kenya and Tanzania)',
'lus': 'Lushai',
'mac': 'Macedonian',
'mad': 'Madurese',
'mag': 'Magahi',
'mah': 'Marshallese',
'mai': 'Maithili',
'mak': 'Makasar',
'mal': 'Malayalam',
'man': 'Mandingo',
'mao': 'Maori',
'map': 'Austronesian (Other)',
'mar': 'Marathi',
'mas': 'Maasai',
'max': 'Manx',
'may': 'Malay',
'mdf': 'Moksha',
'mdr': 'Mandar',
'men': 'Mende',
'mga': 'Irish, Middle (ca. 1100-1550)',
'mic': 'Micmac',
'min': 'Minangkabau',
'mis': 'Miscellaneous languages',
'mkh': 'Mon-Khmer (Other)',
'mla': 'Malagasy',
'mlg': 'Malagasy',
'mlt': 'Maltese',
'mnc': 'Manchu',
'mni': 'Manipuri',
'mno': 'Manobo languages',
'moh': 'Mohawk',
'mol': 'Moldavian',
'mon': 'Mongolian',
'mos': 'Mooré',
'mul': 'Multiple languages',
'mun': 'Munda (Other)',
'mus': 'Creek',
'mwl': 'Mirandese',
'mwr': 'Marwari',
'myn': 'Mayan languages',
'myv': 'Erzya',
'nah': 'Nahuatl',
'nai': 'North American Indian (Other)',
'nap': 'Neapolitan Italian',
'nau': 'Nauru',
'nav': 'Navajo',
'nbl': 'Ndebele (South Africa)',
'nde': 'Ndebele (Zimbabwe)',
'ndo': 'Ndonga',
'nds': 'Low German',
'nep': 'Nepali',
'new': 'Newari',
'nia': 'Nias',
'nic': 'Niger-Kordofanian (Other)',
'niu': 'Niuean',
'nno': 'Norwegian (Nynorsk)',
'nob': 'Norwegian (Bokmål)',
'nog': 'Nogai',
'non': 'Old Norse',
'nor': 'Norwegian',
'nqo': 'N\'Ko',
'nso': 'Northern Sotho',
'nub': 'Nubian languages',
'nwc': 'Newari, Old',
'nya': 'Nyanja',
'nym': 'Nyamwezi',
'nyn': 'Nyankole',
'nyo': 'Nyoro',
'nzi': 'Nzima',
'oci': 'Occitan (post-1500)',
'oji': 'Ojibwa',
'ori': 'Oriya',
'orm': 'Oromo',
'osa': 'Osage',
'oss': 'Ossetic',
'ota': 'Turkish, Ottoman',
'oto': 'Otomian languages',
'paa': 'Papuan (Other)',
'pag': 'Pangasinan',
'pal': 'Pahlavi',
'pam': 'Pampanga',
'pan': 'Panjabi',
'pap': 'Papiamento',
'pau': 'Palauan',
'peo': 'Old Persian (ca. 600-400 B.C.)',
'per': 'Persian',
'phi': 'Philippine (Other)',
'phn': 'Phoenician',
'pli': 'Pali',
'pol': 'Polish',
'pon': 'Pohnpeian',
'por': 'Portuguese',
'pra': 'Prakrit languages',
'pro': 'Provençal (to 1500)',
'pus': 'Pushto',
'que': 'Quechua',
'raj': 'Rajasthani',
'rap': 'Rapanui',
'rar': 'Rarotongan',
'roa': 'Romance (Other)',
'roh': 'Raeto-Romance',
'rom': 'Romani',
'rum': 'Romanian',
'run': 'Rundi',
'rup': 'Aromanian',
'rus': 'Russian',
'sad': 'Sandawe',
'sag': 'Sango (Ubangi Creole)',
'sah': 'Yakut',
'sai': 'South American Indian (Other)',
'sal': 'Salishan languages',
'sam': 'Samaritan Aramaic',
'san': 'Sanskrit',
'sao': 'Samoan',
'sas': 'Sasak',
'sat': 'Santali',
'scc': 'Serbian',
'scn': 'Sicilian Italian',
'sco': 'Scots',
'scr': 'Croatian',
'sel': 'Selkup',
'sem': 'Semitic (Other)',
'sga': 'Irish, Old (to 1100)',
'sgn': 'Sign languages',
'shn': 'Shan',
'sho': 'Shona',
'sid': 'Sidamo',
'sin': 'Sinhalese',
'sio': 'Siouan (Other)',
'sit': 'Sino-Tibetan (Other)',
'sla': 'Slavic (Other)',
'slo': 'Slovak',
'slv': 'Slovenian',
'sma': 'Southern Sami',
'sme': 'Northern Sami',
'smi': 'Sami',
'smj': 'Lule Sami',
'smn': 'Inari Sami',
'smo': 'Samoan',
'sms': 'Skolt Sami',
'sna': 'Shona',
'snd': 'Sindhi',
'snh': 'Sinhalese',
'snk': 'Soninke',
'sog': 'Sogdian',
'som': 'Somali',
'son': 'Songhai',
'sot': 'Sotho',
'spa': 'Spanish',
'srd': 'Sardinian',
'srn': 'Sranan',
'srp': 'Serbian',
'srr': 'Serer',
'ssa': 'Nilo-Saharan (Other)',
'sso': 'Sotho',
'ssw': 'Swazi',
'suk': 'Sukuma',
'sun': 'Sundanese',
'sus': 'Susu',
'sux': 'Sumerian',
'swa': 'Swahili',
'swe': 'Swedish',
'swz': 'Swazi',
'syc': 'Syriac',
'syr': 'Syriac, Modern',
'tag': 'Tagalog',
'tah': 'Tahitian',
'tai': 'Tai (Other)',
'taj': 'Tajik',
'tam': 'Tamil',
'tar': 'Tatar',
'tat': 'Tatar',
'tel': 'Telugu',
'tem': 'Temne',
'ter': 'Terena',
'tet': 'Tetum',
'tgk': 'Tajik',
'tgl': 'Tagalog',
'tha': 'Thai',
'tib': 'Tibetan',
'tig': 'Tigré',
'tir': 'Tigrinya',
'tiv': 'Tiv',
'tkl': 'Tokelauan',
'tlh': 'Klingon (Artificial language)',
'tli': 'Tlingit',
'tmh': 'Tamashek',
'tog': 'Tonga (Nyasa)',
'ton': 'Tongan',
'tpi': 'Tok Pisin',
'tru': 'Truk',
'tsi': 'Tsimshian',
'tsn': 'Tswana',
'tso': 'Tsonga',
'tsw': 'Tswana',
'tuk': 'Turkmen',
'tum': 'Tumbuka',
'tup': 'Tupi languages',
'tur': 'Turkish',
'tut': 'Altaic (Other)',
'tvl': 'Tuvaluan',
'twi': 'Twi',
'tyv': 'Tuvinian',
'udm': 'Udmurt',
'uga': 'Ugaritic',
'uig': 'Uighur',
'ukr': 'Ukrainian',
'umb': 'Umbundu',
'und': 'Undetermined',
'urd': 'Urdu',
'uzb': 'Uzbek',
'vai': 'Vai',
'ven': 'Venda',
'vie': 'Vietnamese',
'vol': 'Volapük',
'vot': 'Votic',
'wak': 'Wakashan languages',
'wal': 'Wolayta',
'war': 'Waray',
'was': 'Washoe',
'wel': 'Welsh',
'wen': 'Sorbian (Other)',
'wln': 'Walloon',
'wol': 'Wolof',
'xal': 'Oirat',
'xho': 'Xhosa',
'yao': 'Yao (Africa)',
'yap': 'Yapese',
'yid': 'Yiddish',
'yor': 'Yoruba',
'ypk': 'Yupik languages',
'zap': 'Zapotec',
'zbl': 'Blissymbolics',
'zen': 'Zenaga',
'zha': 'Zhuang',
'znd': 'Zande languages',
'zul': 'Zulu',
'zun': 'Zuni',
'zxx': 'No linguistic content',
'zza': 'Zaza',
}
}
